Repository karl-cardenas-coding/disaster-cli, pull requests merged in 2020-04, with the labels that each got.

#15 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#17 GitHub
  .github/workflows/build.yml
  .github/workflows/test.yml
  README.md
  cmd/disaster.go
  disaster-cli.md
  documentation/disaster.md
  documentation/disaster_categories.md
  documentation/disaster_events.md
  documentation/disaster_version.md
  go.mod
  go.sum
  library/query_test.go
  library/structs.go
  library/structs_test.go
  release.config.js
Labels: documentation, enhancement, testing

#34 Clean up
  .github/workflows/build.yml
  .github/workflows/test.yml
  cmd/disaster.go
  cmd/version.go
  release.config.js
Labels: CI/CD, documentation, enhancement

#33 test: add json call for test structs
  go.mod
  go.sum
  library/client.go
  library/structs_test.go
Labels: testing

#35 Fix 1
  .github/workflows/build.yml
  .gitignore
  cmd/disaster.go
  cmd/version.go
  library/client.go
  library/structs_test.go
  release.config.js
Labels: bug
